[project]
name = "fb-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "joblib>=1.5.3",
    "pandas>=3.0.0",
    "pymysql>=1.1.2",
    "scikit-learn>=1.8.0",
]
